version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5008:80"
    depends_on:
      - db
  web:
    build: 
      context: .
      dockerfile: Dockerfile-UI
    ports:
      - "8080:8080"
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    ports:
      - "9009:1433"
    environment:
      MSSQL_SA_PASSWORD: "ixnfutDPCM5408*"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"