// <auto-generated />
using Freddy.Persistance.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Freddy.Persistance.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200706110956_ChangeIdToGuid_RemoveIntIdentity")]
    partial class ChangeIdToGuid_RemoveIntIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Freddy.Persistance.Entities.Product", b =>
                {
                    b.Property<int>("OldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OldId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            OldId = 1,
                            Code = "WRUP1LC001, P4",
                            Name = "Fáradt rózsaszín pamut nadrág- csípő",
                            Size = "M"
                        },
                        new
                        {
                            OldId = 2,
                            Code = "WRUP1LC001, N",
                            Name = "Fekete pamut nadrág- csípő",
                            Size = "XL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
