// <auto-generated />
using System;
using Freddy.Persistance.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Freddy.Persistance.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200706111128_ChangeIdToGuid_AddGuidIdentity")]
    partial class ChangeIdToGuid_AddGuidIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Freddy.Persistance.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8e060d6-5cfc-4009-b150-c0870cc45464"),
                            Code = "WRUP1LC001, P4",
                            Name = "Fáradt rózsaszín pamut nadrág- csípő",
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("3b50451a-05d1-4e96-a2d7-7ff1e2cca09f"),
                            Code = "WRUP1LC001, N",
                            Name = "Fekete pamut nadrág- csípő",
                            Size = "XL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
