apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freddytoolapi
  name: freddytoolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freddytoolapi
  template:
    metadata:
      labels:
        app: freddytoolapi
    spec:
      containers:
        - image: DAVIDFEDORK8S.azurecr.io/freddytoolapi:v1
          name: freddytoolapi
          ports:
            - containerPort: 80
---              
apiVersion: v1
kind: Service
metadata:
  name: freddytoolapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: freddytoolapi